spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    schema-registry-url: ${SCHEMA_REGISTRY}
    streams:
      application-id: stock-market-analytics

stock-market-analytics:
  alpha-vantage:
    apiKey: ${ALPHA_VANTAGE_API_KEY}

logging:
  level:
    root: info
server:
  port: 8083